// Generated by apps/desktop/scripts/write-capability-integrity.mjs.
export const WINDOWS_CAPABILITY_BRIDGE_SHA256 = '09a722d3f9423e37cb085ac8dd085a93c8cefa139a0c87f31d65d949542d90ff' as const;
export const WINDOWS_CAPABILITY_BRIDGE_SIZE_BYTES = 59777 as const;
