// Generated by apps/desktop/scripts/write-capability-integrity.mjs.
export const WINDOWS_CAPABILITY_BRIDGE_SHA256 = 'f112589e8f4c5f740f3d5085962e070aacf37d9eb1ac8fd369820696f905623f' as const;
export const WINDOWS_CAPABILITY_BRIDGE_SIZE_BYTES = 60394 as const;
